
# mybatis-plus????
mybatis-plus:
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true
  # mapper????XML????
  mapper-locations: classpath:mapper/**/*.xml
  # ????????????????????????????????????
  type-aliases-package: org.williams.project.modules.*.entity
  # ??mybatis-plus?banner
  global-config:
    banner: false
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  profiles:
    active: dev
jasypt:
  encryptor:
    bean: customStringEncryptor